= Workshop Overview
include::_attributes.adoc[]

[#workshop-layout]
== Workshop Layout

In this workshop each user will have access to three OpenShift Projects, i.e. namespaces, as follows:

* user%USERNUM%-dev. This represents the development environment where we will deploy the application as a vanilla Kubernetes Deployment so
we can compare and contrast it to Rollouts.
* user%USERNUM%-prod. This is our production environment, here we will deploy a Rollout for the application. During the course of the workshop
you will deploy rollouts using different strategies and analysis.
* user%USERNUM%-tools. This is where the CI/CD tooling is located, it contains a pipeline to promote image changes across the development and production
environments. For this workshop we will be using the integrated OpenShift Pipelines feature, this is not core to the workshop but simply provides an easy
way to manage image changes.

[#review-rollout-manager]
== Review RolloutManager Deployment

The OpenShift GitOps Operator simplifies the deployment of Argo Rollouts easy as all tha

To deploy Argo Rollouts using the OpenShift GitOps Operator we need to define and create a RolloutManager
custom resource.
