= Workshop Overview
include::_attributes.adoc[]

[#workshop-layout]
== Workshop Layout

In this workshop each user will have access to three OpenShift Projects, i.e. namespaces, as follows:

* _user%USERNUM%-dev_. This represents the development environment where we will deploy the application as a vanilla Kubernetes Deployment so
we can compare and contrast it to Rollouts.
* _user%USERNUM%-prod_. This is our production environment, here we will deploy a Rollout for the application. During the course of the workshop
you will deploy rollouts using different strategies and analysis.
* _user%USERNUM%-tools_. This is where the CI/CD tooling is located, it contains a pipeline to promote image changes across the development and production
environments. For this workshop we will be using the integrated OpenShift Pipelines feature, this is not core to the workshop but simply provides an easy
way to manage image changes.

[#review-rollout-manager]
== Review RolloutManager Deployment

The OpenShift GitOps Operator simplifies the deployment of Argo Rollouts easy as all tha

To deploy Argo Rollouts using the OpenShift GitOps Operator we need to define and create a RolloutManager
custom resource in the namespace where we want to run the Rollout. In the case of our workshop a
RolloutManager has already been provisioned for you.

[NOTE]
Argo Rollouts can be deployed as ether a namespace or cluster scope, the OpenShift GitOps operator
currently only supports namespace scope.

To review the rollout manager, execute the following command:

[.console-input]
[source,bash,subs="attributes+,+macros"]
----
oc get rolloutmanager argo-rollout -n user%USERNUM%-prod | oc neat
----

[NOTE]
We are using a kubectl plugin called kubectl-neat in order to tidy the yaml by removing
additional fields, labels and annotations added automatically by Kubernetes.

This will return a simple object as follows:

---
apiVersion: argoproj.io/v1alpha1
kind: RolloutManager
metadata:
  name: argo-rollout
  namespace: user1-prod
spec: {}
---
