apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rollouts-demo
  strategy:
    blueGreen:
      activeService: active
      previewService: preview
      autoPromotionEnabled: true
      prePromotionAnalysis:
        args:
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: route-name
          value: preview
        - name: route-url
          value: preview-user%USER%-prod.%SUB_DOMAIN%
        templates:
        - templateName: smoke-tests
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - image: quay.io/openshiftdemos/rollouts-demo:blue
        imagePullPolicy: IfNotPresent
        name: rollouts-demo
        ports:
        - containerPort: 8080
